# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import drone_pb2 as drone__pb2


class MoveDroneStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.move = channel.unary_stream(
        '/MoveDrone/move',
        request_serializer=drone__pb2.Request.SerializeToString,
        response_deserializer=drone__pb2.Response.FromString,
        )
    self.adjust = channel.unary_stream(
        '/MoveDrone/adjust',
        request_serializer=drone__pb2.Request.SerializeToString,
        response_deserializer=drone__pb2.Response.FromString,
        )


class MoveDroneServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def move(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def adjust(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MoveDroneServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'move': grpc.unary_stream_rpc_method_handler(
          servicer.move,
          request_deserializer=drone__pb2.Request.FromString,
          response_serializer=drone__pb2.Response.SerializeToString,
      ),
      'adjust': grpc.unary_stream_rpc_method_handler(
          servicer.adjust,
          request_deserializer=drone__pb2.Request.FromString,
          response_serializer=drone__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MoveDrone', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
